### ISSUE TITLE
Roadmap for django-taggit

### ISSUE THREAD

**Issue by xordoquy** [alex/django-taggit#112]
This ticket will try to aggregate the directions in which efforts will be made to help django taggit move forward.

There are a couple of issues and PR waiting, we need to make sure they are still up to date, make sense or not.
## Performance
#68 [performance]add used_count to Tag
## Case and accents
#98 Ability to force lowercase tags. Management commands to convert mixed case to lowercase tags.
#72 Add a setting for default slugify function
#70 Need settings option FORCE_LOWERCASE_TAGS
## Widgets
#33 Autocomplete widget for the admin.
## To sort
#111    Is there currently a method of deleting tags that are no longer attached to any objects?
#110    Being able to restrict adding tags to just the admin.
#109    Merging django-taggit with django-taggit-templatetags
#105    Tags duplication
#104    Fixing issue when subclassing models
#103    "Related Field has invalid lookup: icontains" in Admin when adding 'tags' to search_fields
#102    'Tag' object has no attribute 'tag' when pass obj.tags in form initial
#101    type object 'TaggedSomething' has no attribute 'tags_for'
#100    Added names method to _TaggableManager
#94 form field issue
#90 TagWidget.render assumes value is queryset
#87 Double quotes in tag name
#84 Cannot resolve keyword 'tagged_items' into field. Choices are: geoloc, id, lat, long
#82 TaggedItem has no field named 'content_object'
#80 KeyError on similar_objects
#76 Create an efficient way to get unique tags for a query set
#75 Getting wrong content_type_id when using Inheritance
#74 TaggedItem has no field named 'content_object'
#73 Add example in the documentation about how to use a custom Tag model
#67 Related Tags
#63 Tag field always appears as 'changed' in Django forms (contains patch)
#57 similar_objects query slow in MySQL for large data sets (suggested fix included)
#50 Issue Adding Multiple TaggableManagers to a Model (or) through parameter does not respect related_name (possible available fix)
#41 Cleanup the tagged items view, make it class based
#32 Further queryset filter parameter for similar_objects method

**Comment by melinath** [comment]
(#57 is performance)

**Comment by bashu** [comment]
+1 for https://github.com/alex/django-taggit/issues/355

**Comment by nemesisdesign** [comment]
This ticket has been open for 4 years, I'm closing this. Feel free to open tickets that address specific issues.
