### ISSUE TITLE
Tags on different applications

### ISSUE THREAD

**Issue by burakk** [alex/django-taggit#150]
I have two applications named blog and web. In blog i have 'entry' model and in web i have 'work' model. Both of those models have TaggableManager field, named 'tags'...

When i want to take the tags of works categorized under 'drawing' and do -->

drawingTags = Tag.objects.filter( work__in = drawings ).distinct()
If there is a drawing with id 1 and if entry model has an entry with id 1. Than i get both item's tags. I have searched on that a lot with no luck. Is this a known issue , is it related with the 'TaggableManager-related_name' problem?

**Comment by andho** [comment]
@burakk thanks I was looking for a way to get the content_type of my model to do exactly this.

**Comment by jdufresne** [comment]
Looks like the original issue has been resolved. Thanks.
