### ISSUE TITLE
Display list of tags and number of times used but for ONLY "open" posts

### ISSUE THREAD

**Issue by deronsizemore** [alex/django-taggit#203]
Hi,

I'm hoping someone still checks this area that might be able to assist. I'm trying to show a list of tags and the number of times the tag has been used but for ONLY "open" posts.

I'm able to use: Post.tags.most_common() which allows me to show the tag and then use the num_times variable to show the number of times the tag has been used.

The problem from there is that I cannot figure out how to show the tag/num_times ONLY for "open" posts. I've got a status field setup in my Post model with three choices, open, draft and closed and want to filter this tag list and num_times by only status='o'

If I use: Post.tags.most_common().filter(post__status='o') it gives me the tag and the number of times but for some reason the num_times outputs the wrong number. I've currently got three Posts and I've tagged each post under "reviews" tag and instead of showing "3" for num_times, it's showing "9." So it seems it's multiplying by itself? 

Any ideas?

**Comment by saritasa** [comment]
Did you find a solution?

**Comment by deronsizemore** [comment]
I did, but not using Django ORM. I'm sure it's possible but I was tired of trying to figure it out and I had a friend who's good with sql so he helped out by writing a query for me to do it. Here's my view for showing all tags and the number of times that tag was used on open posts:

    class TagCloudView(generic.ListView):
	template_name = 'blog/tags.html'
	context_object_name = 'all_tags'

	def get_queryset(self):
		return Tag.objects.raw('Select count(*) as tag_count,tt.name, tt.slug, tt.id from taggit_taggeditem t inner join taggit_tag tt on t.tag_id = tt.id inner join blog_post p on t.object_id = p.id where p.status = \'o\' group by tt.name, tt.slug, tt.id order by tag_count desc')

**Comment by philippbosch** [comment]
[This PR](https://github.com/alex/django-taggit/pull/422) I think fixes this (but was only merged long after this issue was opened).

**Comment by deronsizemore** [comment]
@philippbosch Sorry just now seeing this notification for some reason. Thanks a lot!
