### ISSUE TITLE
Django's m2m_changed signal is not fired 

### ISSUE THREAD

**Issue by roodie** [alex/django-taggit#205]
Django is generally using the m2m_changed event to notify the system if a model's m2m field changes, since the handling of these happens after the model's save event.

https://docs.djangoproject.com/en/dev/ref/signals/#django.db.models.signals.m2m_changed

But django-taggit is not firing this event, which makes it impossible to do any additional processing on the tags upon save. 

The way I tried is:
m2m_changed.connect(tags_changed, sender=News.tags.through)

**Comment by aventurella** [comment]
Has this gotten any further? I would love to use something like this.

**Comment by jpatel3** [comment]
Any good solution for this change. We are also running into issue while using it with Haystack.

**Comment by prydie** [comment]
@frewsxcv I've started work on my implementation of this feature based on core's implementation of [`create_forward_many_to_many_manager()`](https://github.com/django/django/blob/ed0ff913c648b16c4471fc9a9441d1ee48cb5420/django/db/models/fields/related_descriptors.py#L729) and would really appreciate your feedback on my [work thus far](https://github.com/alex/django-taggit/compare/master...the-mediae-co:feature/205-m2m-changed-signal) (there are a number of `#NOTE` and `#TODO` comments).

**Comment by frewsxcv** [comment]
Fixed by https://github.com/alex/django-taggit/pull/409.

**Comment by x007007007** [comment]
I have same bug on 1.9.6
