### ISSUE TITLE
Tag delimiter proposal

### ISSUE THREAD

**Issue by bburan** [alex/django-taggit#215]
Would it be acceptable to suggest a better way of delimiting tags?  Right now the  logic  that determines how a tag string is pretty complex.  If there's a comma, then the tag string is split based on the commas.  Otherwise, the tag string is split based on whitespace.  So, the tag string `Cued Speech, adaptations` will be parsed as two tags (`Cued Speech` and `adaptations`) whereas `Cued Speech` will be parsed as two tags `Cued` and `Speech`.   We recently encountered this issue on our website where some people were attempting to attach a single tag to an item as `Cued Speech`; however, it kept splitting the tag into two tags.  They were pretty confused because on other items when they attempted to attach multiple tags (e.g. `Cued Speech, adaptations, famous people`), the tag list was properly getting parsed into three tags.

In my opinion this is relatively unintuitive behavior for most users.  I would suggest that simplify the approach by adding a regular expression pattern that can be configured via the settings file (e.g. TAGGIT_TAG_DELIMITER).  One could then define a regular expression that splits on all spaces, except when the word is surrounded by quotation marks (e.g. r`(?: |\"(.*?)\"|'.*?')?`.  Alternatively, if one prefers that the split just occur on commas one could define the pattern accordingly (e.g. r'\s*,\s*' to capture the comma and whitespace around the comma).

This would, however, introduce a backwards-incompatible change.  For example, the `parse_tags` function would no longer change its behavior based on whether it detects commas/quotation marks in the string.  Each website would have to decide what an appropriate tag delimiter is and define it accordingly in the settings file.  

Additional work would have to be done for the reverse direction (e.g. `edit_string_for_tags` would need to know how to build the tag string and separator.  This behavior can presumably also be customized via settings (e.g. TAGGIT_TAG_SEPARATOR and TAGGIT_MULTIWORD_QUOTE).  

If there is interest in implementing this, please let me know and I'd be happy to submit a PR.

**Comment by gEndelf** [comment]
+1

**Comment by bburan** [comment]
The PR is ready to merge once it's reviewed and accepted. I think I successfully rebased off of master but am not 100% sure I did it properly. @gEndelf, if you try out the pull request and like it, can you comment? This may help get it accepted.
