### ISSUE TITLE
IntegrityError on accented tags

### ISSUE THREAD

**Issue by ajendrex** [alex/django-taggit#277]
Hello,

I added the tag "Gestion"  and saved an object. Then I edited another object and tried to add the tag "Gestión" (with the proper accent), but I have an unhandled IntegrityError from the mysql connector. I think this is a bug. For now, I think I will try removing accents before saving, but that's not what I want.

Thanks for any help,
Hector.

**Comment by jdufresne** [comment]
You can install the package Unidecode to solve this:

- https://pypi.org/project/Unidecode/
- https://github.com/takluyver/Unidecode

If the library is present, the slug will be normalized using it. It should solve your issue:

```
>>> from unidecode import unidecode
>>> unidecode("Gestión")
'Gestion'
```

Unfortunately, this isn't very well documented. Are you interested in contributing a documentation update to fix issue #348?
