### ISSUE TITLE
Bad JOIN collumn on tagging Inerited models

### ISSUE THREAD

**Issue by martende** [alex/django-taggit#282]
I have some simple inherited model
```
class Page(models.Model):
....
class Game(Page):
....
    tags = TaggableManager()
```
i I try to make 
```
games = Game.objects.filter(tags__name__in = [tagname])
```
I receive
OperationalError: (1054, "Unknown column 'game.id' in 'on clause'")

**Comment by frewsxcv** [comment]
0.16.1 has been released that includes this fix

https://pypi.python.org/pypi/django-taggit/0.16.1
