### ISSUE TITLE
Any workaround for the lookup error in Django 1.7.6?

### ISSUE THREAD

**Issue by chawk** [alex/django-taggit#296]
I've tried to upgrade to the latest version of Django.  django-taggit cannot be migrated and throws this error. 

/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 94, in render
    raise ValueError(msg.format(field=operations[0][1], model=lookup_model))
ValueError: Lookup failed for model referenced by field article.Article.tags: taggit.Tag

**Comment by chawk** [comment]
The only way I was able to get around this issue was by deleting all previous migrations dropping the tables and installing Taggit first.  Than I was able to add the previous tables in migrate without getting the lookup error.  I'll try to look into this further, but I know Django 1.7 has had some open bugs regarding foreign key problems with migrations.

**Comment by jdufresne** [comment]
django-taggit has dropped support for Django 1.7 and the master branch now supports Django 1.11, 2.0, and 2.1. If you're still able to reproduce, please re-open with full details using an updated version. Thanks.
