### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by loimu** [alex/django-taggit#312]
When there's only one tag or only one tagged item the following line throws an error

```
  File "/home/xxx/.local/lib/python3.4/site-packages/taggit_templatetags/templatetags/taggit_extras.py", line 45, in weight_fun
    mult_fac = float(t_max-t_min)/float(f_max-f_min)
ZeroDivisionError: float division by zero
```

tested on django-taggit v0.11.2 and newer

**Comment by jdufresne** [comment]
This looks like an issue with the django-taggit-templatetags project, not this one. See upstream issue: https://github.com/feuervogel/django-taggit-templatetags/issues/24
