### ISSUE TITLE
RemovedInDjango19Warning

### ISSUE THREAD

**Issue by jonathanng** [alex/django-taggit#317]
Would be great if we could remove these warnings:

	C:\Anaconda\lib\site-packages\taggit\models.py:87: RemovedInDjango19Warning: Model class taggit.models.Tag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
		  class Tag(TagBase):

	WARN:py.warnings:C:\Anaconda\lib\site-packages\taggit\models.py:87: RemovedInDjango19Warning: Model class taggit.models.Tag doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
		  class Tag(TagBase):

	C:\Anaconda\lib\site-packages\taggit\models.py:192: RemovedInDjango19Warning: Model class taggit.models.TaggedItem doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
		  class TaggedItem(GenericTaggedItemBase, TaggedItemBase):

	WARN:py.warnings:C:\Anaconda\lib\site-packages\taggit\models.py:192: RemovedInDjango19Warning: Model class taggit.models.TaggedItem doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
		  class TaggedItem(GenericTaggedItemBase, TaggedItemBase):

**Comment by frewsxcv** [comment]
This should have been fixed in https://github.com/alex/django-taggit/pull/385
