### ISSUE TITLE
Required composit index for "taggit_taggeditem" table!

### ISSUE THREAD

**Issue by pahaz** [alex/django-taggit#318]
For improving query performance, required to add a composite index like so:

    CREATE INDEX "taggit_taggeditem_faster" ON "taggit_taggeditem" ("object_id", "content_type_id");

SQLite test:

    Food.objects.filter(tags__name__in=['t2']).exclude(tags__name__in=['f2'])  # time: 0.386 (without index)
    Food.objects.filter(tags__name__in=['t2']).exclude(tags__name__in=['f2'])  # time: 0.001 (with index)
    # count(Food) = ~ 400 000, count(Tag) = ~ 200, count(TaggedItem) = ~ 2 000 000
    # ~ 5 tags per Food item

**Comment by frewsxcv** [comment]
Fixed by #319
