### ISSUE TITLE
'TaggableRel' object has no attribute 'through_fields' in Django 1.8.2

### ISSUE THREAD

**Issue by pacahon** [alex/django-taggit#321]
When I try to open admin page, it crashes with `TaggableRel' object has no attribute 'through_fields'`.
I can add this attribute to TaggableRel class to fix this error, but to be honest I have no idea is it ok to do it in that way.

**Comment by jcalazan** [comment]
+1 Ran into this issue as well in the admin, adding `through_fields = None` seems to have fixed it.

**Comment by frewsxcv** [comment]
Fixed in #328 

Just published 0.16.2 that includes the fix

https://pypi.python.org/pypi/django-taggit/0.16.2
