### ISSUE TITLE
Unicode Slugs for Unicode Tags

### ISSUE THREAD

**Issue by avorio** [alex/django-taggit#356]
I have encountered so many problems using unicode tags and slugs.

See, for example, *Different unicode but same slug exception error* #340.

I just came across [django-uuslug](https://github.com/un33k/django-uuslug) and wondered whether we could incorporate it for unicode slugs for unicode tags. Or is this not the right scope?

**Comment by frewsxcv** [comment]
Have you tried installing `unidecode`? https://github.com/alex/django-taggit/issues/348

**Comment by frewsxcv** [comment]
@avorio Did `unidecode` fix your issues?

**Comment by avorio** [comment]
Hi @frewsxcv, I have not tried installing it yet, no.

But isn't this we would like to include by default in `django-taggit`?

**Comment by frewsxcv** [comment]
> But isn't this feature something we would like to include by default in django-taggit?

No, unidecode is licensed under the GPL and django-taggit is BSD, this can't happen (see also #273).
