### ISSUE TITLE
drop support of all versions less then 1.8

### ISSUE THREAD

**Issue by auvipy** [alex/django-taggit#369]
i will be happy to send pr

**Comment by frewsxcv** [comment]
1.4 just became unsupported not too long ago. Ideally we'd cut off support for <1.8 to encourage people to upgrade to maintained versions of Django, but I feel it's a little too soon.

**Comment by auvipy** [comment]
i think we can drop support for 1.4, 1.5 and 1.6 :) with your green signal i could send pr too

**Comment by frewsxcv** [comment]
Works for me :+1:

**Comment by auvipy** [comment]
ok will send pr

**Comment by auvipy** [comment]
https://github.com/alex/django-taggit/pull/386

**Comment by prydie** [comment]
@auvipy Dropping support for older versions of Django is no good unless we remove the code related to supporting those versions. Without doing so we will keep a lot of technical debt. Is this something you would be able/willing to look into?

**Comment by auvipy** [comment]
yess @prydie

**Comment by prydie** [comment]
@auvipy Excellent. Feel free to @ reply me in any PR(s).

**Comment by stringsonfire** [comment]
So aggregation would be supported?

**Comment by timgraham** [comment]
This was half done in https://github.com/alex/django-taggit/pull/386 and finished in https://github.com/alex/django-taggit/pull/435.
