### ISSUE TITLE
TaggedItem' object has no attribute '+'

### ISSUE THREAD

**Issue by alexsilva** [alex/django-taggit#378]
AttributeError at /xadmin/auth/group/
'TaggedItem' object has no attribute '+'

taggit 1.80.0

Django 1.7
xadmin (branch django1.7)
python2.7

When trying to delete groups containing tags the error occurs.
This was marked as resolved but it seems not.

https://github.com/alex/django-taggit/issues/172

**Comment by frewsxcv** [comment]
Can you reproduce this error with the native Django admin (not xadmin)?

**Comment by alexsilva** [comment]
I made a test project and work properly with django 1.7 and 1.9.
Just that I need taggit in xadmin have no way to solve this ?

**Comment by alexsilva** [comment]
![capturar](https://cloud.githubusercontent.com/assets/2024086/12726862/0aef7b38-c901-11e5-81b1-35f9126fd08f.PNG)
It's a very similar error that has now been resolved

**Comment by alexsilva** [comment]
https://github.com/django/django/blob/stable/1.7.x/django/db/models/deletion.py#L206
The problem is related to version 1.7 django.

**Comment by frewsxcv** [comment]
Django 1.7 is not supported anymore. You should really upgrade

**Comment by alexsilva** [comment]
I managed to fix the bug making the changes below in xadmin, but this seems to be a problem in django collector.

>     def collect(self, objs, source_attr=None, **kwargs):
        for obj in objs:
            #if source_attr:
            if source_attr and hasattr(obj, source_attr): # here!
                self.add_edge(getattr(obj, source_attr), obj)
            else:
                self.add_edge(None, obj)
        try:
            return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)
        except models.ProtectedError, e:
            self.protected.update(e.protected_objects)

**Comment by alexsilva** [comment]
taggit works with django 1.7.11!
My django is 1.7.7 - I will try to do this update

**Comment by frewsxcv** [comment]
> taggit works with django 1.7.11

Not for too much longer https://github.com/alex/django-taggit/issues/369

Django 1.7 is unsecure and no longer maintained by the [DSF](https://www.djangoproject.com/foundation/). I strongly encourage you to upgrade to Django 1.8.

**Comment by alexsilva** [comment]
Ok I'll try.
But I do not have a project here, but a larger framework that django itself.
It is a very large structure.
