### ISSUE TITLE
Currently failing in django 1.9

### ISSUE THREAD

**Issue by tutuca** [alex/django-taggit#381]
django.template.library.InvalidTemplateLibrary: Invalid template library specified.
    ImportError raised when trying to load 'taggit_templatetags.templatetags.taggit_extras': No module named  'django.db.models.loading'

**Comment by frewsxcv** [comment]
Closing since this looks like an issue with https://github.com/feuervogel/django-taggit-templatetags.

**Comment by frewsxcv** [comment]
You might have luck with https://github.com/fizista/django-taggit-templatetags2 though I haven't used it.
