### ISSUE TITLE
Switch to compiler.quote_name_unless_alias

### ISSUE THREAD

**Issue by orokusaki** [alex/django-taggit#383]
Running:

```
Spam.objects.aggregate(models.Count('tags'))
```

Produces this warning:

> [taggit/managers.py:87](https://github.com/alex/django-taggit/blob/develop/taggit/managers.py#L87): RemovedInDjango110Warning: Calling a SQLCompiler directly is deprecated. Call compiler.quote_name_unless_alias instead.

This isn't an issue yet, but I wanted to log it here, because it will be an issue with Django 1.10.

**Comment by collinanderson** [comment]
See #380

**Comment by orokusaki** [comment]
Ah. Thanks, Colin. Somehow, I missed that issue when I did an issue search.

**Comment by jdufresne** [comment]
Looks like this has already been fixed. Thanks for reporting. If you continue to see an issue, please add additional information.
