### ISSUE TITLE
Form field doesn't show up in modelforms in django master

### ISSUE THREAD

**Issue by jpic** [alex/django-taggit#384]
In current django master, taggit's form field doesn't show up anymore.

In Django 1.9:

![2016-03-23-233110_634x226_scrot](https://cloud.githubusercontent.com/assets/94636/14002944/8f9729d2-f14f-11e5-9aa6-45061fbb3594.png)

In Django master (14e6823):

![2016-03-23-232846_618x152_scrot](https://cloud.githubusercontent.com/assets/94636/14002919/6bae34de-f14f-11e5-83d4-fca4c2a94100.png)

I've uploaded a test project if you want to experiment with it (admin login: test, admin pass: test1231): https://github.com/jpic/test_taggit

Perhaps Django is applying a design decision that was made a while ago ([django/#16286](https://code.djangoproject.com/ticket/16286)).

Is this expected ?

**Comment by jpic** [comment]
This is the commit in django that causes this: https://github.com/django/django/commit/983c158da7723eb00a376bd31db76709da4d0260

**Comment by collinanderson** [comment]
I believe we should just need to add `many_to_many = True`.

**Comment by jpic** [comment]
That's what it *looks* like indeed ;)

**Comment by collinanderson** [comment]
Ahh, I see we already have `many_to_many = True`

**Comment by jpic** [comment]
We need many_to_many=False for this specific problem.

There's another issue with django master i'll make a separate issue.

Then we're good B)

**Comment by jpic** [comment]
If we set many_to_many=False then a lot of other things such as saving breaks ...

I guess we've been checkmated here xD

**Comment by collinanderson** [comment]
Fascinating. From Django's point of view it would be nice if there was a way to control this. It seems like `many_to_many` is good for almost everything _except_ the admin. Maybe the admin's formfield_for_manytomany should check isinstance(field, ManyToMany), and keep the many_to_many check everywhere else.

**Comment by jpic** [comment]
The form field now shows up.
