### ISSUE TITLE
Remove check for Django <1.3

### ISSUE THREAD

**Issue by frewsxcv** [alex/django-taggit#388]
https://github.com/alex/django-taggit/blob/58c675dd4b331eda6c9e301a1bbb7a2f7ea51044/tests/tests.py#L47-L56

We don't support anything less than Django 1.3, so this can be removed.

**Comment by auvipy** [comment]
pr send https://github.com/alex/django-taggit/pull/387

**Comment by frewsxcv** [comment]
Can you make it a separate pull request?

**Comment by auvipy** [comment]
OK will try

**Comment by frewsxcv** [comment]
Done in https://github.com/alex/django-taggit/pull/390
