### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by prydie** [alex/django-taggit#407]
We should agree on guidelines for contributing to the project. The generally accepted norm is to provide a `CONTRIBUTING` file in the root of the repository with basic instructions on how/what to contribute to the repository.

Some initial suggestions would include:
- All code should pass linting by `flake8` (configuration provided)
- Contributors should make every effort not to decrease the test coverage of the project in their submissions

**Comment by frewsxcv** [comment]
Hi @prydie! I'm the current maintainer for django-taggit.

> I am reticent to invest time writing too much code that won't be accepted upstream (I don't have the time nor inclination to independently maintain a fork).

I don't have much time to dedicate to this project, but I'm generally accepting with regards to bugfixes and small feature additions.

> potentially start a discussion resulting in the drawing up of a CONTRIBUTING.md.

Would love this :)

> Coding style: Will pull requests that tidy up code (structurally) be entertained and if so do the maintainers have any preferences in this area?

flake8 gets run on all pull requests.

https://github.com/alex/django-taggit/blob/master/.travis.yml#L42

> Tooling: the project could potentially benefit from improvements in development tooling. Off the top of my head py.test, mock, and isort are examples. I'm particularly interested in the incorporation of mock as it will make testing signal handling significantly cleaner.

I have not preferences here. If you want to expand the testsuite, I won't stop you :)

I know one thing that would be nice would be code coverage integration (e.g. coveralls, codecov.io)

**Comment by prydie** [comment]
Hi @frewsxcv! Thanks for the prompt response. Nice to e-meet you.

> I don't have much time to dedicate to this project, but I'm generally accepting with regards to bugfixes and small feature additions.

Good to know.

> flake8 gets run on all pull requests.

Interesting; my linter (`flake8` via [syntastic](https://github.com/scrooloose/syntastic)) throws up `E302` (correctly) in a number of places but running `flake8 taggit` does indeed result in no issues.

> I have not preferences here. If you want to expand the testsuite, I won't stop you :)

Excellent hopefully I'll land something worth reviewing tomorrow.

>  I know one thing that would be nice would be code coverage integration (e.g. coveralls, codecov.io)

coveralls integration would be great but I believe only @alex can set that up for this repository (I may very well be wrong).

**Comment by frewsxcv** [comment]
> Interesting; my linter (flake8 via syntastic) throws up E302 (correctly) in a number of places but running flake8 taggit does indeed result in no issues.

FYI https://github.com/alex/django-taggit/blob/master/setup.cfg#L7-L14

**Comment by frewsxcv** [comment]
Also, according to Alex, this repository should already have Codecov.io enabled on the code coverage front, we just need to add it in Travis. I personally prefer Codecov over Coveralls.

**Comment by prydie** [comment]
> FYI https://github.com/alex/django-taggit/blob/master/setup.cfg#L7-L14

Ooops. I noticed the import ordering issues and lack of `.isort.cfg` and didn't explore further.

**Comment by frewsxcv** [comment]
I *can* access the upload token, but it shouldn't be necessary. I think all you need to do is add

```yml
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

to the `.travis.yml` file.

**Comment by frewsxcv** [comment]
Do you think this issue can be closed?

**Comment by prydie** [comment]
> Do you think this issue can be closed?

Possibly. Either that or we could re-purpose it as a ticket for the production of a `CONTRIBUTING.md`. Thoughts?

**Comment by frewsxcv** [comment]
> Possibly. Either that or we could re-purpose it as a ticket for the production of a CONTRIBUTING.md. 

SGTM

**Comment by prydie** [comment]
I've updated the issue accordingly.

**Comment by nemesisdesign** [comment]
A pull-request regarding contribution guidelines has been merged: #480, so I'm closing this.
