### ISSUE TITLE
Loading existing tags within a fixture

### ISSUE THREAD

**Issue by swdelaney2** [alex/django-taggit#413]
Is there any way to load tags as part of a fixture? And if not, what would be the best way to migrate them?

**Comment by prydie** [comment]
Personally, I have been moving away from fixtures towards [data migrations](https://docs.djangoproject.com/en/1.9/topics/migrations/#data-migrations). I find fixtures more brittle and harder to keep up-to-date with schema modifications. You should be able to achieve `Tag` creation through a data migration pretty easily.

**Comment by frewsxcv** [comment]
Django seems to be phasing out fixtures in favor of data migrations. I agree with @prydie's answer.
