### ISSUE TITLE
Add commits from 'develop' branch into 'master'

### ISSUE THREAD

**Issue by frewsxcv** [alex/django-taggit#425]
https://github.com/alex/django-taggit/compare/master...develop?expand=1

I just realized that some commits (see link above) were added on `develop` branch, but not `master`. The `develop` branch is no longer being used and should be avoided. The commits above (by @auvipy) should be cherry picked onto `master` so we drop support for those old Django versions.

**Comment by frewsxcv** [comment]
I'm not actively working on this, so if someone wants to take care of this, please do! If not, I'll eventually get around to it.

**Comment by nickhudkins** [comment]
Perhaps when I fix the migrations in #424 I can do this at the same time.

**Comment by frewsxcv** [comment]
If it makes your life easier, don't worry about [that CHANGELOG formatting commit](c3b845483893db9c2ead49fb86bd4d3dde0d48d0).

**Comment by auvipy** [comment]
right
