### ISSUE TITLE
Tag description field

### ISSUE THREAD

**Issue by meshekhar** [alex/django-taggit#442]
I would like to have a Tag description field so that a tag can be described in detail similar to the stackoverflow tag function. How can i add a custom field?

Could it be considered a future enhancement?

**Comment by prydie** [comment]
The [Customising Taggit docs](http://django-taggit.readthedocs.io/en/latest/custom_tagging.html#using-a-custom-tag-or-through-model) it

**Comment by frewsxcv** [comment]
I think @prydie has the right answer here, so closing this.
