### ISSUE TITLE
taggit not working with Djnago1.9

### ISSUE THREAD

**Issue by kaligithub** [alex/django-taggit#447]
When I migrate the DB then below error comes:
  File "C:\Anaconda2\lib\site-packages\taggit\managers.py", line 55, in **init**
    self.to = to
AttributeError: can't set attribute

**Comment by frewsxcv** [comment]
Which version of taggit?

**Comment by frewsxcv** [comment]
https://github.com/alex/django-taggit/issues/351 seems relevant.
