### ISSUE TITLE
'_TaggableManager' object has no attribute 'name'

### ISSUE THREAD

**Issue by zivanovicb** [alex/django-taggit#459]
`for member in members:
		print member.customuser.skills`

When I try to get skills which are `skills = TaggableManager()` in models.py I get:

`AttributeError at /members/
'_TaggableManager' object has no attribute 'name'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/members/
Django Version:	1.10.4
Exception Type:	AttributeError
Exception Value:	
'_TaggableManager' object has no attribute 'name'
Exception Location:	C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\db\models\manager.py in __str__, line 39
Python Executable:	C:\Users\zivan\Desktop\lobokus-django\Scripts\python.exe
Python Version:	2.7.13
Python Path:	
['C:\\Users\\zivan\\Desktop\\lobokus-django\\lobokus',
 'C:\\Windows\\SYSTEM32\\python27.zip',
 'C:\\Users\\zivan\\Desktop\\lobokus-django\\DLLs',
 'C:\\Users\\zivan\\Desktop\\lobokus-django\\lib',
 'C:\\Users\\zivan\\Desktop\\lobokus-django\\lib\\plat-win',
 'C:\\Users\\zivan\\Desktop\\lobokus-django\\lib\\lib-tk',
 'C:\\Users\\zivan\\Desktop\\lobokus-django\\Scripts',
 'c:\\python27\\Lib',
 'c:\\python27\\DLLs',
 'c:\\python27\\Lib\\lib-tk',
 'C:\\Users\\zivan\\Desktop\\lobokus-django',
 'C:\\Users\\zivan\\Desktop\\lobokus-django\\lib\\site-packages']
Server time:	Tue, 17 Jan 2017 22:44:42 +0100`

Traceback:

` Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/members/

Django Version: 1.10.4
Python Version: 2.7.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'projects.apps.ProjectsConfig',
 'users.apps.UsersConfig',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.twitter',
 'allauth.socialaccount.providers.facebook',
 'allauth.socialaccount.providers.github',
 'taggit',
 'haystack',
 'django_countries']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\handlers\exception.py" in inner
  39.             response = get_response(request)

File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\handlers\base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\core\handlers\base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\zivan\Desktop\lobokus-django\lobokus\users\views.py" in members
  36. 		print member.customuser.skills

File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\utils\six.py" in <lambda>
  842.         klass.__str__ = lambda self: self.__unicode__().encode('utf-8')

File "C:\Users\zivan\Desktop\lobokus-django\lib\site-packages\django\db\models\manager.py" in __str__
  39.         return '%s.%s' % (self.model._meta.label, self.name)

Exception Type: AttributeError at /members/
Exception Value: '_TaggableManager' object has no attribute 'name'
`

**Comment by frewsxcv** [comment]
Which version of taggit? Which version of Django?

**Comment by zivanovicb** [comment]
Thank you for fast reply!
Django==1.10.4
django-taggit==0.21.3

**Comment by frewsxcv** [comment]
This might be helpful? https://django-taggit.readthedocs.io/en/latest/admin.html#including-tags-in-modeladmin-list-display

**Comment by zivanovicb** [comment]
Thank you! `member.customuser.skills.all()` worked
