### ISSUE TITLE
install/migration issue

### ISSUE THREAD

**Issue by danieldeiana** [alex/django-taggit#484]
Good day

When running: 

**python manage.py makemigrations blog**

I'm getting the following error:

**ModuleNotFoundError: No module named 'taggit'**

I have later then Django 1.8 installed:

**(b) PS C:\dan_projects\django_by_example_blog\mysite> pip freeze
Django==1.8.6
django-taggit==0.22.1
pytz==2017.2**

And 'taggit' has been added to my installed_apps:

**INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'taggit',
)**

In my _models.py_ file I've imported it:

**from taggit.managers import TaggableManager**

Apologies if I'm doing something silly, I am a novice and any help would be greatly appreciated!

**Comment by gnahum12345** [comment]
What was the fix? I am having the same issue right now
