### ISSUE TITLE
Create "Related Post" based on Tags

### ISSUE THREAD

**Issue by alzearafat** [alex/django-taggit#485]
Hi there!

I'm new in django/python, so please bear with me.

I want to create some sort of "Related Post" in django. How I can do that? I'm following this : [How to fetch related items when using taggit in django?](http://stackoverflow.com/questions/30144220/how-to-fetch-related-items-when-using-taggit-in-django)

but dont know how to use/implement it and how to render it in template. This is my view :

```
def trip_single(request, slug):
    trip = get_object_or_404(Trip, slug=slug)
    related_trip = Trip.objects.filter(misc_published=True, tags=trip.tags.similar_objects())[:3]
    return render(request, 'app_trip/trip_single.html', {'trip': trip, 'related_trip': related_trip})
```

I want to make something like this : 
```
# Loop a trip, related to the post based on Tags

{% for trip in related_trip %}
   <h1>{{ trip.title }}</h1>
{% endfor %}
```

Any help would be greatly appreciated
Thank you!

**Comment by nemesisdesign** [comment]
@alzearafat I think it's better you post this kind of question on [stackoverflow](https://stackoverflow.com/), we use this place to track bugs to the code.

**Comment by alzearafat** [comment]
@nemesisdesign Nevermind, solved it!
