### ISSUE TITLE
multiple databases support?

### ISSUE THREAD

**Issue by enapupe** [alex/django-taggit#498]
Hello.
I currently have a read-replica database where I access some model instances that have taggit. Is there any way to define which database taggit will save to?
I'm looking for something like:
`instance.tags.using('another_db').add(tag_obj)`

Thanks!

**Comment by enapupe** [comment]
Ops, apparently my suggestion actually works, probably because django manager already supports it.

**Comment by vdboor** [comment]
In case someone bumps into this, the following also works:

```
from taggit.models import TaggedItem


class OtherDBTaggedItem(TaggedItem):
    """
    This proxy model is routed to use a different database.
    """

    class Meta:
        proxy = True

class SomeModel(models.Model):
    tags = TaggableManager(blank=True, through=OtherDBTaggedItem)
```

A custom `DATABASE_ROUTERS` can now detect whether the standard `TaggedItem`, or `OtherDBTaggedItem` is used to access the tags. For example, when redirecting all models from one specific `app_label` to a different database, the tags will be part of that as well.
