### ISSUE TITLE
In django 2.1 TagWidget fails to render due to unexpected keyword argument

### ISSUE THREAD

**Issue by andrlik** [alex/django-taggit#535]
self = <django.forms.boundfield.BoundField object at 0x10a958f28>, widget = <taggit.forms.TagWidget object at 0x10a958ef0>
attrs = {'id': 'id_tags'}, only_initial = False

    def as_widget(self, widget=None, attrs=None, only_initial=False):
        """
            Render the field by rendering the passed widget, adding any HTML
            attributes passed as attrs. If a widget isn't specified, use the
            field's default widget.
            """
        widget = widget or self.field.widget
        if self.field.localize:
            widget.is_localized = True
        attrs = attrs or {}
        attrs = self.build_widget_attrs(attrs, widget)
        if self.auto_id and 'id' not in widget.attrs:
            attrs.setdefault('id', self.html_initial_id if only_initial else self.auto_id)
        return widget.render(
            name=self.html_initial_name if only_initial else self.html_name,
            value=self.value(),
            attrs=attrs,
>           renderer=self.form.renderer,
        )
E       TypeError: render() got an unexpected keyword argument 'renderer'

.tox/py36-django21/lib/python3.6/site-packages/django/forms/boundfield.py:93: TypeError

The fix is to change widget's render function to accept `renderer` as an argument and then based on Django version, pass that as well to `super()` call.

There are multiple valid approaches already submitted that could work with this such as PR #518 , PR #505 , or PR #534. However, there aren't any issues for them, so creating one here.

**Comment by collinanderson** [comment]
#518 is merged, so this is fixed now

**Comment by jdufresne** [comment]
Thanks for the report. This has been fixed on master.

**Comment by Zulqarnain-tech** [comment]
Just found another simple solution of this problem. Just comment out the line
renderer=self.form.renderer,
This approach worked fine for me.
