### ISSUE TITLE
Need settings option FORCE_LOWERCASE_TAGS

### ISSUE THREAD

**Issue by shacker** [alex/django-taggit#70]
Slugs are lowercased by being passed through slugify, but tag names are not. Thus some users can enter "Music" and others enter "music" - these are functionally identical, but taggit creates two tags "music" and "music_1", and tag listings and clouds of course show both versions, which is confusing. 

Django-tagging has a global settings option to force all lowercase tags and I'd love to see the same in Taggit.

**Comment by frewsxcv** [comment]
Case insensitive tags was added in https://github.com/alex/django-taggit/pull/325 and is available in the latest version of taggit (0.16.0)
