### ISSUE TITLE
TaggedItem has no field named 'content_object'

### ISSUE THREAD

**Issue by vitorcarvalhoml** [alex/django-taggit#82]
Hello, I have this model.py:
 23 class Article(models.Model):
 24     title = models.CharField(max_length=200)
 25     slug = models.SlugField(max_length=100, blank=True)
 26     category_name = models.ForeignKey(Category)
 27     content = models.TextField()
 28     tags = TaggableManager()
 29     pub_date = models.DateTimeField(default=datetime.now())

In my view, I did this:
 30     noticias_relacionadas = Article.objects.filter(tags__name_in=["pediatria"]
But, I get this error..
Exception Type:     FieldDoesNotExist
Exception Value:    TaggedItem has no field named 'content_object'

**Comment by jdufresne** [comment]
This looks like a duplicate of #74. If you're still experiencing this issue, can you please provide updated details in that ticket?
